# -*- coding: utf-8 -*-
"""مرز اتصال دیتابیس گیسو — SQLite (فعلی/پشتیبان) ↔ PostgreSQL (اصلی، پس از تأیید).

طرح مصوب: PG تنها نویسنده است؛ SQLite فقط آرتیفکت پشتیبانِ یک‌طرفه.
این ماژول فقط «مرز» است: تشخیص انجین، ترجمهٔ placeholder/DDL، سازگاری‌سازی
توابع تاریخ SQLite روی PG، و یک adapter سبک که همان API رشته‌کلیدی sqlite3
را روی PG ارائه می‌دهد تا بقیهٔ کد دست‌نخورده بماند.
هیچ رفتاری بدون ست‌کردن env تغییر نمی‌کند (پیش‌فرض همیشه sqlite).
"""
import os
import re

ENGINE_ENV = "GISO_DB_ENGINE"          # sqlite | postgres
GISO_DSN_ENV = "GISO_PG_DSN"           # postgresql://user:pass@host:5432/giso_db
BOT_DSN_ENV = "BOT_EDU_PG_DSN"         # postgresql://user:pass@host:5432/bot_edu_db


def is_pg(kind: str = "giso") -> bool:
    """فقط وقتی true که صریحاً env ست شده باشد؛ پیش‌فرض مطلق sqlite."""
    return os.environ.get(ENGINE_ENV, "sqlite").strip().lower() == "postgres"


def dsn_for(kind: str = "giso") -> str:
    return os.environ.get(GISO_DSN_ENV if kind == "giso" else BOT_DSN_ENV, "").strip()


# ── ترجمهٔ placeholder: sqlite «?» ↔ psycopg «%s» ──
def translate_placeholders(sql: str) -> str:
    return (sql or "").replace("?", "%s")


_PRAGMA_RE = re.compile(r"^\s*PRAGMA\b", re.I)


def is_pragma(sql: str) -> bool:
    return bool(_PRAGMA_RE.match(sql or ""))


# ── ترجمهٔ DDL SQLite → PG (برای ابزار مهاجرت و CREATEهای زمان‌اجرا) ──
def translate_ddl_sqlite_to_pg(ddl: str) -> str:
    out = ddl or ""
    out = re.sub(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
                 "BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY", out, flags=re.I)
    # در SQLite ستون INTEGER PRIMARY KEY حتی بدون AUTOINCREMENT خودکار شماره می‌گیرد؛
    # معادل PG آن IDENTITY است (BY DEFAULT تا درج شناسهٔ صریح — مثل بازیابی بکاپ — مجاز بماند).
    out = re.sub(r"\bINTEGER\s+PRIMARY\s+KEY\b",
                 "BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY", out, flags=re.I)
    out = re.sub(r"\bAUTOINCREMENT\b", "", out, flags=re.I)
    # INTEGER در SQLite هشت‌بایتی است؛ INTEGER در PG چهاربایتی → سرریز برای شناسه‌های
    # بزرگ (مثل bale_id). همهٔ INTEGERهای باقی‌مانده به BIGINT نگاشت می‌شوند.
    out = re.sub(r"\bINTEGER\b", "BIGINT", out, flags=re.I)
    out = re.sub(r"\bBLOB\b", "BYTEA", out, flags=re.I)
    out = re.sub(r"\bREAL\b", "DOUBLE PRECISION", out, flags=re.I)
    return out


# ── توابع سازگاری تاریخ SQLite روی PG تا رشته‌SQLها دوانجینه بمانند ──
SQLITE_COMPAT_PG_FUNCTIONS = """
CREATE OR REPLACE FUNCTION datetime(ts text) RETURNS text AS $$
  SELECT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS');
$$ LANGUAGE SQL STABLE;
CREATE OR REPLACE FUNCTION datetime(ts text, mod text) RETURNS text AS $$
  SELECT to_char(
    CASE
      WHEN mod IN ('localtime', 'now', '') THEN CURRENT_TIMESTAMP
      WHEN mod ~ '^[+-]?\\d+ (years|months|days|hours|minutes|seconds|year|month|day|hour|minute|second)$'
        THEN CURRENT_TIMESTAMP + mod::interval
      ELSE CURRENT_TIMESTAMP
    END, 'YYYY-MM-DD HH24:MI:SS');
$$ LANGUAGE SQL STABLE;
"""


# ── adapter سبک: همان API sqlite3 روی psycopg2 (ردیف‌های رشته‌کلیدی+اندیسی) ──
class PgRow:
    __slots__ = ("_cols", "_vals")

    def __init__(self, cols, vals):
        self._cols = cols
        self._vals = vals

    def keys(self):
        return list(self._cols)

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._vals[key]
        return self._vals[self._cols.index(key)]

    def __contains__(self, key):
        return key in self._cols

    def __iter__(self):
        return iter(self._vals)

    def __len__(self):
        return len(self._vals)


class PgCursor:
    def __init__(self, cur):
        self._cur = cur

    def execute(self, sql, params=()):
        sql = (sql or "").strip()
        if is_pragma(sql):
            # PRAGMA table_info → معادل واقعی روی information_schema (۴۱ مصرف
            # در مهاجرت‌های تنبل ADD COLUMN)؛ ستون‌ها: cid,name,type,notnull,dflt,pk
            m = re.match(r"(?is)^PRAGMA\s+table_info\s*\(\s*[\"'\[]?([\w]+)[\"'\]]?\s*\)$", sql)
            if m:
                self._cur.execute(
                    "SELECT (ordinal_position-1), column_name, data_type, "
                    "CASE WHEN is_nullable='NO' THEN 1 ELSE 0 END, column_default, 0 "
                    "FROM information_schema.columns "
                    "WHERE table_name=%s ORDER BY ordinal_position",
                    (m.group(1),))
                return self
            if re.match(r"(?is)^PRAGMA\s+(integrity_check|quick_check)", sql):
                self._cur.execute("SELECT 'ok'")
                return self
            return self  # بقیهٔ PRAGMAها (WAL و...) روی PG بی‌معنا → no-op
        sql = sql.replace("BEGIN IMMEDIATE", "BEGIN")
        if re.match(r"(?is)^(CREATE|ALTER)\b", sql):
            # ساخت جدول تنبل در زمان اجرا با گویش SQLite نوشته شده → ترجمهٔ DDL
            sql = translate_ddl_sqlite_to_pg(sql)
        self._last_id = None
        self._consumed = False
        tsql = translate_placeholders(sql)
        if re.match(r"(?is)^INSERT\b", sql) and "RETURNING" not in sql.upper():
            # lastrowid در sqlite؛ در PG با RETURNING id شبیه‌سازی می‌شود.
            # اگر جدول ستون id نداشته باشد، بی‌صدا به درج ساده برمی‌گردیم.
            try:
                self._cur.execute("SAVEPOINT giso_lid")
                self._cur.execute(tsql + " RETURNING id", tuple(params or ()))
                row = self._cur.fetchone()
                self._last_id = row[0] if row else None
                self._cur.execute("RELEASE SAVEPOINT giso_lid")
                self._consumed = True
                return self
            except Exception:
                try:
                    self._cur.execute("ROLLBACK TO SAVEPOINT giso_lid")
                except Exception:
                    pass
        self._cur.execute(tsql, tuple(params or ()))
        return self

    def executemany(self, sql, seq):
        self._cur.executemany(translate_placeholders(sql), [tuple(p) for p in seq])
        return self

    def _rows(self):
        cols = [d[0] for d in self._cur.description] if self._cur.description else []
        return cols

    def fetchone(self):
        if getattr(self, "_consumed", False):
            return None
        r = self._cur.fetchone()
        return PgRow(self._rows(), r) if r is not None else None

    def fetchall(self):
        if getattr(self, "_consumed", False):
            return []
        cols = self._rows()
        return [PgRow(cols, r) for r in self._cur.fetchall()]

    @property
    def rowcount(self):
        return self._cur.rowcount

    @property
    def lastrowid(self):
        return getattr(self, "_last_id", None)

    def close(self):
        self._cur.close()


class PgConn:
    """حداقل API مورد استفادهٔ کد فعلی: execute/executemany/commit/rollback/close + with."""

    def __init__(self, dsn: str, close_on_exit: bool = False):
        import psycopg2
        self._conn = psycopg2.connect(dsn)
        self._close_on_exit = close_on_exit

    def execute(self, sql, params=()):
        return PgCursor(self._conn.cursor()).execute(sql, params)

    def executemany(self, sql, seq):
        return PgCursor(self._conn.cursor()).executemany(sql, seq)

    def executescript(self, script):
        """معادل sqlite3: اجرای چند دستور پشت‌هم (تفکیک ';' بیرون از لیترال‌ها)."""
        stmts, buf, in_str = [], [], False
        for ch in script or "":
            if ch == "'":
                in_str = not in_str
            if ch == ";" and not in_str:
                stmts.append("".join(buf))
                buf = []
            else:
                buf.append(ch)
        if "".join(buf).strip():
            stmts.append("".join(buf))
        for st in stmts:
            if st.strip():
                self.execute(st)
        self.commit()

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, *a):
        try:
            if exc_type is None:
                self.commit()
            else:
                self.rollback()
        finally:
            # الگوی گیسو: with → بستن خودکار اتصال (جلوگیری از نشتی FD)
            if self._close_on_exit:
                self.close()
        return False


def connect_pg(kind: str = "giso", close_on_exit: bool = False) -> PgConn:
    dsn = dsn_for(kind)
    if not dsn:
        raise RuntimeError("DSN PostgreSQL ست نشده است (GISO_PG_DSN / BOT_EDU_PG_DSN).")
    return PgConn(dsn, close_on_exit=close_on_exit)


def install_pg_compat(conn: PgConn) -> None:
    """نصب توابع سازگاری تاریخ؛ یک‌بار پس از ساخت اسکیمای PG."""
    cur = conn._conn.cursor()
    cur.execute(SQLITE_COMPAT_PG_FUNCTIONS)
    conn.commit()
